// <auto-generated />
using System;
using BANA.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BANA.Migrations.Dmi
{
    [DbContext(typeof(DmiContext))]
    partial class DmiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("BANA.Models.Dmi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Etat")
                        .HasColumnType("TEXT");

                    b.Property<string>("Glycemie_capillaire")
                        .HasColumnType("TEXT");

                    b.Property<string>("Medecin")
                        .HasColumnType("TEXT");

                    b.Property<string>("Patient")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroDeFacture")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroDossier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pbd")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pbg")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Poids")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rpm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Saturation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Taille")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tdiasbd")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tdiasbg")
                        .HasColumnType("TEXT");

                    b.Property<string>("Temperature")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Trumps")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tsysbd")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tsysbg")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Dmi");
                });
#pragma warning restore 612, 618
        }
    }
}
