// <auto-generated />
using System;
using BANA.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BANA.Migrations.Fiche5
{
    [DbContext(typeof(Fiche5Context))]
    [Migration("20250912221741_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("BANA.Models.Fiche5", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Etat")
                        .HasColumnType("TEXT");

                    b.Property<string>("Medecin")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroDossier")
                        .HasColumnType("TEXT");

                    b.Property<string>("Patient")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pc")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Trumps")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Fiche5");
                });
#pragma warning restore 612, 618
        }
    }
}
