// <auto-generated />
using System;
using BANA.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BANA.Migrations.Hospi
{
    [DbContext(typeof(HospiContext))]
    [Migration("20250816101036_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("BANA.Models.Hospi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActesMedicaux")
                        .HasColumnType("TEXT");

                    b.Property<string>("Adresse")
                        .HasColumnType("TEXT");
                        
                    b.Property<string>("Numero_facture")
                        .HasColumnType("TEXT");
                    

                    b.Property<string>("Allergies")
                        .HasColumnType("TEXT");

                    b.Property<string>("Antecedents")
                        .HasColumnType("TEXT");

                    b.Property<string>("Assurance")
                        .HasColumnType("TEXT");

                    b.Property<string>("Chambre")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CoutSejour")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateAdmission")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateSortie")
                        .HasColumnType("TEXT");

                    b.Property<string>("Destination")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiagnosticAdmission")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiagnosticSortie")
                        .HasColumnType("TEXT");

                    b.Property<string>("EtatSortie")
                        .HasColumnType("TEXT");

                    b.Property<string>("EvolutionClinique")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExamensEtResultats")
                        .HasColumnType("TEXT");

                    b.Property<int>("FrequenceRespiratoire")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroupeSanguin")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lit")
                        .HasColumnType("TEXT");

                    b.Property<string>("MedecinResponsable")
                        .HasColumnType("TEXT");

                    b.Property<string>("MotifAdmission")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .HasColumnType("TEXT");

                    b.Property<string>("NotesInfirmieres")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroHospitalisation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero_dossier")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrdonnanceSortie")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PaiementEffectue")
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonneContactUrgence")
                        .HasColumnType("TEXT");

                    b.Property<int>("Pouls")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prescriptions")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResumeMedical")
                        .HasColumnType("TEXT");

                    b.Property<int>("SaturationOxygene")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Service")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sexe")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SoldeRestant")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .HasColumnType("TEXT");

                    b.Property<string>("TelephoneContactUrgence")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Temperature")
                        .HasColumnType("TEXT");

                    b.Property<string>("TensionArterielle")
                        .HasColumnType("TEXT");

                    b.Property<string>("TraitementsEnCours")
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeHospitalisation")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Hospi");
                });
#pragma warning restore 612, 618
        }
    }
}
