// <auto-generated />
using System;
using BANA.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BANA.Migrations.Fiche4
{
    [DbContext(typeof(Fiche4Context))]
    partial class Fiche4ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("BANA.Models.Fiche4", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Etat")
                        .HasColumnType("TEXT");

                    b.Property<string>("Medecin")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroDossier")
                        .HasColumnType("TEXT");

                    b.Property<string>("Patient")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pc")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Trumps")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("infirmere")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Fiche4");
                });
#pragma warning restore 612, 618
        }
    }
}
