// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BANA.Migrations.Paid
{
    [DbContext(typeof(PaidContext))]
    partial class PaidContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.4");

            modelBuilder.Entity("BANA.Models.Paid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Caissier")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Create_date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Frais_retrait")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Montant")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Moyen_paiement")
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero_dossier")
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero_facture")
                        .HasColumnType("TEXT");

                    b.Property<string>("Numerocaution")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Patient")
                        .HasColumnType("TEXT");

                    b.Property<string>("caisse")
                        .HasColumnType("TEXT");

                    b.Property<string>("fact_type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Paid");
                });
#pragma warning restore 612, 618
        }
    }
}
