// <auto-generated />
using System;
using BANA.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BANA.Migrations.Parametre
{
    [DbContext(typeof(ParametreContext))]
    [Migration("20250807160512_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("BANA.Models.Parametre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Create_date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Glycemie_capillaire")
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero_Dossier")
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero_Facture")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Patient")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pbd")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pbg")
                        .HasColumnType("TEXT");

                    b.Property<string>("Poids")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rpm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Saturation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Taille")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tdiasbd")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tdiasbg")
                        .HasColumnType("TEXT");

                    b.Property<string>("Temperature")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tsysbd")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tsysbg")
                        .HasColumnType("TEXT");
                    b.Property<string>("Infirmier")
                        .HasColumnType("TEXT");
                    b.Property<string>("Pt")
                        .HasColumnType("TEXT");
                    b.Property<string>("Pb")
                        .HasColumnType("TEXT");
                        
                    b.Property<string>("Pc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Parametre");
                });
#pragma warning restore 612, 618
        }
    }
}
