// <auto-generated />
using System;
using BANA.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BANA.Migrations.LNME
{
    [DbContext(typeof(LNMEContext))]
    partial class LNMEContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("BANA.Models.LNME", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Catégorie")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Create_date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dosage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Forme")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .HasColumnType("TEXT");

                    b.Property<string>("DCI")
                        .HasColumnType("TEXT");

                    b.Property<bool>("actif")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("LNME");
                });
#pragma warning restore 612, 618
        }
    }
}
