// <auto-generated />
using System;
using BANA.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BANA.Migrations.Ronde
{
    [DbContext(typeof(RondeContext))]
    partial class RondeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("BANA.Models.Ronde", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DerniereModif")
                        .HasColumnType("TEXT");

                    b.Property<string>("Epj")
                        .HasColumnType("TEXT");

                    b.Property<string>("Etat")
                        .HasColumnType("TEXT");

                    b.Property<string>("Medecin")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroDossier")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroHospi")
                        .HasColumnType("TEXT");
                        

                    b.Property<string>("Parametres")
                        .HasColumnType("TEXT");

                    b.Property<string>("Patient")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Plainte")
                        .HasColumnType("TEXT");

                    b.Property<string>("Taf")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Trumps")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Trumps2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Trumps3")
                        .IsRequired()
                        .HasColumnType("TEXT");
                    
                    b.PrimitiveCollection<string>("Trumps4")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ronde");
                });
#pragma warning restore 612, 618
        }
    }
}
