// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BANA.Migrations.Facture
{
    [DbContext(typeof(FactureContext))]
    [Migration("20230629152112_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.4");

            modelBuilder.Entity("BANA.Models.Facture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Assur_Adresse")
                        .HasColumnType("TEXT");

                    b.Property<string>("Assur_BP")
                        .HasColumnType("TEXT");

                    b.Property<string>("Assur_NIU")
                        .HasColumnType("TEXT");

                    b.Property<string>("Assur_Rc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Assur_Tel")
                        .HasColumnType("TEXT");

                    b.Property<string>("Assureur")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Create_date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Date_entree")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Date_sortie")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Date_validite")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Derniere_impression")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Derniere_modification")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Encaisse_par")
                        .HasColumnType("TEXT");

                    b.Property<int>("Especes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Etat_assurance")
                        .HasColumnType("TEXT");

                    b.Property<string>("Etat_patient")
                        .HasColumnType("TEXT");

                    b.Property<string>("Facture_par")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupeSanguin")
                        .HasColumnType("TEXT");

                    b.Property<string>("Intervenant")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ligne_facturation1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ligne_facturation2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ligne_facturation3")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ligne_facturation4")
                        .HasColumnType("TEXT");

                    b.Property<string>("MatriculeADH")
                        .HasColumnType("TEXT");

                    b.Property<string>("Matricule_patient")
                        .HasColumnType("TEXT");

                    b.Property<string>("Medecin")
                        .HasColumnType("TEXT");

                    b.Property<string>("Montant_en_lettre")
                        .HasColumnType("TEXT");

                    b.Property<string>("Montant_en_lettre_assurance")
                        .HasColumnType("TEXT");

                    b.Property<string>("Montant_en_lettre_patient")
                        .HasColumnType("TEXT");

                    b.Property<int>("Montant_recu_assurance")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Montant_recu_patient")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Moyen_paiement")
                        .HasColumnType("TEXT");

                    b.Property<int>("Net_a_payer_assurance")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Net_a_payer_patient")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Nombre_affichage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Nombre_impression")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero_de_facture")
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero_dossier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<int>("Pourcentage_Assurance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prenom")
                        .HasColumnType("TEXT");

                    b.Property<string>("Profession")
                        .HasColumnType("TEXT");

                    b.Property<string>("Quartier")
                        .HasColumnType("TEXT");

                    b.Property<int>("Remise")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Societe")
                        .HasColumnType("TEXT");

                    b.Property<string>("Taille")
                        .HasColumnType("TEXT");

                    b.Property<float>("Taxe1")
                        .HasColumnType("REAL");

                    b.Property<string>("Titre1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titre2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titre3")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titre4")
                        .HasColumnType("TEXT");

                    b.Property<int>("Total_ht")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Total_ttc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tva")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("assure_prin")
                        .HasColumnType("TEXT");

                    b.Property<int>("frais_retrait")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ticketmoderateur")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Facture");
                });
#pragma warning restore 612, 618
        }
    }
}
