// <auto-generated />
using System;
using BANA.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BANA.Migrations.Fiche
{
    [DbContext(typeof(FicheContext))]
    partial class FicheContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("BANA.Models.Fiche", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categorie")
                        .HasColumnType("TEXT");

                    b.Property<string>("Contenu")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Create_date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Dernieremodification")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .HasColumnType("TEXT");

                    b.Property<string>("Trump1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Trump2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Trump3")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Fiche");
                });
#pragma warning restore 612, 618
        }
    }
}
