// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BANA.Migrations.TransactionStock
{
    [DbContext(typeof(TransactionStockContext))]
    partial class TransactionStockContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.4");

            modelBuilder.Entity("BANA.Models.TransactionStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Create_date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Emplacement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom_article")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Observation")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantitee")
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeOperation")
                        .HasColumnType("TEXT");

                    b.Property<string>("utilisateur")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TransactionStock");
                });
#pragma warning restore 612, 618
        }
    }
}
