// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BANA.Migrations.Resultat
{
    [DbContext(typeof(ResultatContext))]
    [Migration("20230604190437_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.4");

            modelBuilder.Entity("BANA.Models.Resultat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Age_patient")
                        .HasColumnType("TEXT");

                    b.Property<string>("Categorie")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("Contenu")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cote")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Create_date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Date_de_finalisation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date_de_naissance")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExamType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .HasColumnType("TEXT");

                    b.Property<int>("Montant")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomPatient")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroDossier")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroFacture")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prescripteur")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone_patient")
                        .HasColumnType("TEXT");

                    b.Property<string>("fait_par")
                        .HasColumnType("TEXT");

                    b.Property<string>("resultat_final")
                        .HasColumnType("TEXT");

                    b.Property<string>("valide_par")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Resultat");
                });
#pragma warning restore 612, 618
        }
    }
}
