// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BANA.Migrations.Stock
{
    [DbContext(typeof(StockContext))]
    partial class StockContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.4");

            modelBuilder.Entity("BANA.Models.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Actif")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categorie")
                        .HasColumnType("TEXT");

                    b.Property<string>("Compte_general")
                        .HasColumnType("TEXT");

                    b.Property<string>("Compte_general_entree")
                        .HasColumnType("TEXT");

                    b.Property<string>("Compte_general_sortie")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Create_date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Img")
                        .HasColumnType("TEXT");

                    b.Property<int?>("In")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastModification")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lieu_stockage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom_article")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Out")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Prix_achat")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Prix_vente")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Quantitee")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference")
                        .HasColumnType("TEXT");

                    b.Property<string>("Societe")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Stock_minimal")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Vendu")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("chiffre_affaire")
                        .HasColumnType("TEXT");

                    b.Property<string>("codebarre")
                        .HasColumnType("TEXT");

                    b.Property<string>("unité")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Stock");
                });
#pragma warning restore 612, 618
        }
    }
}
